server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=UTC
    hikari:
      username: root
      password: root
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver  但是6.x以后使用这个也没问题
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: BJ
  application:
        name: content-center
  # 允许一个server拥有多个feign客户端
  main:
    allow-bean-definition-overriding: true
ribbon:
  eager-load:
    enabled: true
    clients: user-center,xxx
logging:
  level:
    # 只有feign接口声明为debug级别才可以正常打印日志
    com.goblin.contentcenter.feignclient.UserCenterFeignClient: debug
    com.goblin.contentcenter.feignclient.TestUserCenterFeignClient: debug
feign:
  client:
    config:
      # 微服务名称,default为全局配置
      default:
        loggerLevel: full
  httpclient:
    # feign使用apache httpclient做请求代替默认的urlconnention（也可以使用okhttp）
    enabled: true
    # feign最大连接数（这两个值的最优配置，可以参考压测结果）
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'